/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CriticalGC */

#ifndef _Included_CriticalGC
#define _Included_CriticalGC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CriticalGC
 * Method:    acquire
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_CriticalGC_acquire
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     CriticalGC
 * Method:    release
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_CriticalGC_release
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
